/* Yuki · Biblioteca cultural · V1 */
(function(){
'use strict';
const KEY='biblioteca';
const cargarB=window.cargar||function(k,d){try{return JSON.parse(localStorage.getItem('yuki_'+k))||d}catch(e){return d}};
const guardarB=window.guardar||function(k,v){localStorage.setItem('yuki_'+k,JSON.stringify(v))};
const escB=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const urlB=v=>{try{const u=new URL(String(v||'').trim());return /^https?:$/.test(u.protocol)?u.href:''}catch(e){return ''}};
const normB=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/\s+/g,' ');
const tagsB=v=>(Array.isArray(v)?v:String(v||'').split(',')).map(x=>x.trim().toUpperCase()).filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i);
const listaB=()=>{const x=cargarB(KEY,[]);return Array.isArray(x)?x:[]};
const guardarListaB=x=>{guardarB(KEY,x);renderB()};
const avisoB=t=>{if(typeof window.toast==='function')window.toast(t);else{const e=document.getElementById('biblioteca-aviso');if(e){e.textContent=t;e.hidden=false;setTimeout(()=>e.hidden=true,2500)}}};
function crearNavegacionB(){
 if(document.getElementById('tab-biblioteca'))return;
 const musica=[...document.querySelectorAll('nav button')].find(b=>b.getAttribute('onclick')?.includes("tab('musica'"));
 if(musica){const b=document.createElement('button');b.type='button';b.textContent='Biblioteca';b.setAttribute('onclick',"tab('biblioteca',this)");musica.parentElement.appendChild(b)}
 const panel=document.createElement('div');panel.id='tab-biblioteca';panel.className='tab';panel.hidden=true;panel.setAttribute('aria-hidden','true');
 panel.innerHTML=`<div class="card"><div class="card-title">📚 Biblioteca · leer, ver y escuchar</div><p class="hobby-lead">Tu archivo cultural. Conserva la fuente original y abre cada contenido fuera de Yuki.</p></div><div class="card"><div class="card-title">⚡ Guardar algo</div><div class="biblioteca-grid"><input id="bib-titulo" placeholder="Título"><input id="bib-creador" placeholder="Autor, artista, director o creador"><select id="bib-categoria"><option value="leer">LEER</option><option value="ver">VER</option><option value="escuchar">ESCUCHAR</option></select><input id="bib-tipo" placeholder="Tipo: libro, documental, álbum…"><input id="bib-original" placeholder="Enlace original · Instagram, web, Drive…"><input id="bib-youtube" placeholder="Enlace YouTube u otra plataforma (opcional)"><input id="bib-fuente" placeholder="Fuente: Instagram, recomendación, conversación…"><input id="bib-tags" placeholder="Etiquetas: jazz, documental, noche…"></div><textarea id="bib-descripcion" rows="2" placeholder="Por qué te interesa o qué quieres recordar"></textarea><div class="biblioteca-form-foot"><select id="bib-estado"><option value="pendiente">Pendiente</option><option value="en curso">En curso</option><option value="terminado">Terminado</option><option value="favorito">Favorito</option></select><button class="btn btn-primary btn-sm" type="button" id="bib-guardar">Guardar en Biblioteca</button></div><p id="biblioteca-aviso" class="choice-note" hidden></p></div><div class="card"><div class="card-title">Buscar y filtrar</div><div class="biblioteca-grid biblioteca-filtros"><input id="bib-buscar" placeholder="Buscar título, creador o etiqueta"><select id="bib-filtro-cat"><option value="">Todas las categorías</option><option value="leer">Leer</option><option value="ver">Ver</option><option value="escuchar">Escuchar</option></select><select id="bib-filtro-estado"><option value="">Todos los estados</option><option value="pendiente">Pendiente</option><option value="en curso">En curso</option><option value="terminado">Terminado</option><option value="favorito">Favorito</option></select></div></div><div id="biblioteca-lista"></div>`;
 const ref=document.querySelector('.tab');if(ref)ref.parentNode.insertBefore(panel,ref);
 document.getElementById('bib-guardar').addEventListener('click',guardarBiblio);
 ['bib-buscar','bib-filtro-cat','bib-filtro-estado'].forEach(id=>document.getElementById(id).addEventListener('input',renderB));
}
function limpiarFormB(){['bib-titulo','bib-creador','bib-tipo','bib-original','bib-youtube','bib-fuente','bib-tags','bib-descripcion'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=''});document.getElementById('bib-categoria').value='leer';document.getElementById('bib-estado').value='pendiente'}
function guardarBiblio(){
 const titulo=document.getElementById('bib-titulo').value.trim(),creador=document.getElementById('bib-creador').value.trim();if(!titulo){avisoB('Escribe un título');return}
 const item={id:String(Date.now()),titulo,creador,categoria:document.getElementById('bib-categoria').value,tipo:document.getElementById('bib-tipo').value.trim(),enlaceOriginal:urlB(document.getElementById('bib-original').value),enlaceYoutube:urlB(document.getElementById('bib-youtube').value),fuente:document.getElementById('bib-fuente').value.trim(),tags:tagsB(document.getElementById('bib-tags').value),descripcion:document.getElementById('bib-descripcion').value.trim(),estado:document.getElementById('bib-estado').value,fecha:new Date().toISOString()};
 const list=listaB(),same=list.find(x=>normB(x.titulo)===normB(item.titulo)&&normB(x.creador)===normB(item.creador)&&x.categoria===item.categoria);
 if(same){['enlaceOriginal','enlaceYoutube'].forEach(k=>{if(item[k]&&same[k]!==item[k])same[k]=same[k]?same[k]+'\n'+item[k]:item[k]});same.tags=tagsB([...(same.tags||[]),...item.tags]);same.fuente=same.fuente||item.fuente;same.descripcion=same.descripcion||item.descripcion;same.updatedAt=new Date().toISOString();guardarListaB(list);avisoB('Ya existía: he actualizado la ficha');limpiarFormB();return}
 list.unshift(item);guardarListaB(list);avisoB('Guardado en Biblioteca');limpiarFormB();
}
function etiquetaB(t){return `<span class="tag-pill">${escB(t)}</span>`}
function enlacesB(item){const vals=[];if(urlB(item.enlaceOriginal))vals.push(`<a href="${escB(urlB(item.enlaceOriginal))}" target="_blank" rel="noopener">Fuente ↗</a>`);if(urlB(item.enlaceYoutube))vals.push(`<a href="${escB(urlB(item.enlaceYoutube))}" target="_blank" rel="noopener">Abrir ↗</a>`);return vals.join(' · ')}
function renderB(){
 const out=document.getElementById('biblioteca-lista');if(!out)return;const q=normB(document.getElementById('bib-buscar')?.value),cat=document.getElementById('bib-filtro-cat')?.value||'',est=document.getElementById('bib-filtro-estado')?.value||'';
 const data=listaB().filter(x=>(!q||normB([x.titulo,x.creador,x.descripcion,(x.tags||[]).join(' ')].join(' ')).includes(q))&&(!cat||x.categoria===cat)&&(!est||x.estado===est));
 out.innerHTML=data.length?data.map(x=>{const catLabel={leer:'LEER',ver:'VER',escuchar:'ESCUCHAR'}[x.categoria]||x.categoria;return `<div class="card biblioteca-item"><div class="biblioteca-item-head"><div><span class="bib-cat">${catLabel}</span><strong>${escB(x.titulo)}</strong>${x.creador?`<small>${escB(x.creador)}</small>`:''}</div><select aria-label="Estado" onchange="window.yukiBibliotecaEstado('${escB(x.id)}',this.value)"><option ${x.estado==='pendiente'?'selected':''}>pendiente</option><option ${x.estado==='en curso'?'selected':''}>en curso</option><option ${x.estado==='terminado'?'selected':''}>terminado</option><option ${x.estado==='favorito'?'selected':''}>favorito</option></select></div>${x.tipo?`<p class="bib-meta">${escB(x.tipo)}</p>`:''}${x.descripcion?`<p>${escB(x.descripcion)}</p>`:''}<div>${tagsB(x.tags).map(etiquetaB).join('')}</div><div class="biblioteca-item-foot"><span>${enlacesB(x)}</span><span><button class="btn-link" onclick="window.yukiBibliotecaEditar('${escB(x.id)}')">Editar</button><button class="btn-link danger" onclick="window.yukiBibliotecaBorrar('${escB(x.id)}')">Borrar</button></span></div></div>`}).join(''):'<div class="card"><p class="book-note">Todavía no hay contenidos que coincidan.</p></div>';
}
window.yukiBibliotecaEstado=(id,v)=>{const l=listaB(),x=l.find(a=>a.id===id);if(x){x.estado=v;guardarListaB(l)}};
window.yukiBibliotecaBorrar=id=>{if(!confirm('¿Borrar esta entrada de la Biblioteca?'))return;guardarListaB(listaB().filter(x=>x.id!==id))};
window.yukiBibliotecaEditar=id=>{const l=listaB(),x=l.find(a=>a.id===id);if(!x)return;const n=prompt('Notas o descripción',x.descripcion||'');if(n!==null){x.descripcion=n;x.updatedAt=new Date().toISOString();guardarListaB(l)}};
const css=document.createElement('style');css.textContent=`.biblioteca-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:8px}.biblioteca-grid input,.biblioteca-grid select,.biblioteca-form-foot select{min-width:0}.biblioteca-form-foot{display:flex;gap:8px;align-items:center;justify-content:flex-end}.biblioteca-filtros{grid-template-columns:2fr 1fr 1fr}.biblioteca-item-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.biblioteca-item-head strong,.biblioteca-item-head small{display:block}.biblioteca-item-head small{color:var(--texto-suave);margin-top:4px}.bib-cat{display:inline-block;font-size:11px;font-weight:800;letter-spacing:.7px;color:var(--verde);margin-right:8px}.bib-meta{color:var(--texto-suave);font-size:13px}.biblioteca-item-foot{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-top:12px;font-size:13px}.biblioteca-item-foot a{color:var(--azul);font-weight:700}.btn-link{border:0;background:none;color:var(--azul);cursor:pointer;font:inherit;margin-left:10px}.btn-link.danger{color:var(--rojo)}@media(max-width:600px){.biblioteca-grid,.biblioteca-filtros{grid-template-columns:1fr}.biblioteca-form-foot{justify-content:stretch;flex-wrap:wrap}.biblioteca-form-foot button{flex:1}.biblioteca-item-head{flex-direction:column}}`;
document.head.appendChild(css);
function init(){crearNavegacionB();renderB()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
